include $(srctree)/drivers/misc/mediatek/Makefile.custom


# In case the platform does NOT support this type of sensors
obj-y   +=  mtk_tpd.o
obj-y   +=  tpd_button.o
obj-y   +=  tpd_calibrate.o
obj-y   +=  tpd_debug.o
obj-y   +=  tpd_default.o
obj-y   +=  tpd_init.o
obj-y   +=  tpd_misc.o
obj-y   +=  tpd_setting.o

obj-$(CONFIG_MTK_SYNAPTICS_3320)	+=  synaptics_3320_letv/

obj-$(CONFIG_MTK_SYNAPTICS_3320U)	+=  synaptics_3320u_letv/

obj-$(CONFIG_MTK_ATMEL_MXT)	+=  atmel_mxt/
